version: 2
jobs:
  build:
    working_directory: ~/MoodleSites
    docker:
      - image: circleci/node:argon-stretch-browsers
    environment:
      - BUCKET_NAME: "moodle.sites.lambda.deployment"
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: code-coverage
          command: 'npm run cover'
    
      - run:
          name: increment version by patch
          command: 'npm version patch'

      - run:
          name: package tar ball
          command: 'npm pack'
      
      - run:
          name: install npm login
          command: 'npm install -g npm-cli-login'

      - run:
          name: npm login
          command: 'npm-cli-login'

      - run:
          name: npm public
          command: 'npm publish'

      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml